#!/usr/bin/env bash
# Install the Layer 1 git pre-commit hook (RM-003 AC5).
#
# The generated hook runs the HERMETIC validators on every commit:
#   - skills/authoring-skills/scripts/validate_skill.py --all  (skill structure)
#   - scripts/verify.mjs                                       (eval-manifest schema)
#   - scripts/check_typed_evals.py --base HEAD                 (new/changed evals
#     must carry a typed `expect` block — RM-003 pass 5, AC17/AC19)
#   - yamllint -c .yamllint.yaml .github/workflows/            (workflow YAML —
#     if yamllint is installed locally; otherwise warns and skips, and CI
#     quality-gates enforces it regardless)
#
# It is advisory: bypassable with `git commit --no-verify`. It costs zero CI
# minutes and catches malformed skills/manifests/workflows before a commit
# (~15s).
#
# Usage:
#   bash scripts/install-hooks.sh
#
# Uninstall:
#   rm .git/hooks/pre-commit

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="${REPO_ROOT}/.git/hooks/pre-commit"

if [[ ! -d "${REPO_ROOT}/.git" ]]; then
    echo "error: not a git repository" >&2
    exit 1
fi

cat > "${HOOK_PATH}" <<'EOF'
#!/usr/bin/env bash
# Layer 1 pre-commit hook — hermetic validators only.
# Generated by scripts/install-hooks.sh; do not edit this file directly.
# Advisory: bypass with `git commit --no-verify` (not recommended).
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

fail() {
    echo "pre-commit: $1 failed" >&2
    echo "  fix the errors above, or bypass with 'git commit --no-verify' (not recommended)" >&2
    exit 1
}

echo "Layer 1 pre-commit: running hermetic validators"

echo "  -> validate_skill.py --all"
python3 "${REPO_ROOT}/skills/authoring-skills/scripts/validate_skill.py" --all || fail "validate_skill.py"

echo "  -> verify.mjs"
node "${REPO_ROOT}/scripts/verify.mjs" || fail "verify.mjs"

echo "  -> check_typed_evals.py --base HEAD"
python3 "${REPO_ROOT}/scripts/check_typed_evals.py" --base HEAD || fail "check_typed_evals.py"

if python3 -m yamllint --version >/dev/null 2>&1; then
    echo "  -> yamllint (.github/workflows/)"
    python3 -m yamllint -c "${REPO_ROOT}/.yamllint.yaml" "${REPO_ROOT}/.github/workflows/" || fail "yamllint"
else
    echo "  -> yamllint skipped (not installed locally — pip install yamllint; CI quality-gates still enforces it)"
fi

echo "Layer 1 pre-commit: all validators passed"
EOF

chmod +x "${HOOK_PATH}"
echo "Installed pre-commit hook at ${HOOK_PATH}"
echo "It runs validate_skill.py --all, scripts/verify.mjs, and check_typed_evals.py on every commit."
